/*!
The functions available in the Plugin WASM runtime.
The types used here are generated by [super::bindings_generator].
*/

use atomic_bindings::*;

pub fn log(msg: String) {
    println!("Provider log: {}", msg);
}

pub fn my_complex_imported_function(a: ComplexAlias) -> ComplexHostToGuest {
    make_host_to_guest()
}

pub fn my_plain_imported_function(a: u32, b: u32) -> u32 {
    a + b
}

pub fn count_words(string: String) -> Result<u16, String> {
    Ok(1337)
}

pub async fn my_async_imported_function() -> ComplexHostToGuest {
    make_host_to_guest()
}

pub fn make_host_to_guest() -> ComplexHostToGuest {
    ComplexHostToGuest {
        simple: Simple {
            bar: "asd".to_owned(),
            foo: 0,
        },
        list: vec![],
        points: vec![],
        recursive: vec![],
        complex_nested: None,
        r#type: "Foobar".to_owned(),
        value: Value::Integer(1),
    }
}

pub async fn make_request(opts: RequestOptions) -> Result<Response, RequestError> {
    Err(RequestError::Other {
        reason: "Not yet implemented".to_owned(),
    })
}
