VERSION 0.7
PROJECT ontola/atomic-server
FROM node:20.8.0-bookworm
WORKDIR browser

all:
  BUILD +build
  BUILD +test
  BUILD +lint
  BUILD +typedoc

deps:
  RUN curl -fsSL https://bun.sh/install | bash
  COPY package.json bun.lockb .
  COPY data-browser/package.json data-browser/.
  COPY lib/package.json lib/.
  COPY react/package.json react/.
  COPY svelte/package.json svelte/.
  COPY cli/package.json cli/.
  RUN bun install --frozen-lockfile
  COPY . .

test:
  FROM +deps
  RUN bun run build
  RUN bun run test

lint:
  FROM +deps
  RUN bun run lint

build:
  FROM +deps
  RUN bun run build
  SAVE ARTIFACT ./data-browser/dist

typedoc:
  FROM +build
  RUN --secret NETLIFY_AUTH_TOKEN=NETLIFY_TOKEN pnpm run typedoc-publish
