### Get a thing as JSON
GET https://atomicdata.dev/properties/isA HTTP/1.1
Accept: application/json

### Get a thing as JSON-AD
GET https://atomicdata.dev/properties/isA HTTP/1.1
Accept: application/ad+json

### Get a thing as JSON-LD
GET https://atomicdata.dev/properties/isA HTTP/1.1
Accept: application/ld+json

### Get a thing as turtle
GET https://atomicdata.dev/properties/isA HTTP/1.1
Accept: text/turtle

### Full text search
GET http://localhost/search?q=test HTTP/1.1
Accept: application/ld+json

### Full text search, return full resource bodies. A bit slower, but could actually result in a faster UX.
GET http://localhost/search?q=test&include=true HTTP/1.1
Accept: application/ld+json

### Index at (RDF) document for search
POST http://localhost/search HTTP/1.1
Content-Type: text/turtle

@prefix schema: <http://schema.org/> .
    <http://example.com/foo> a schema:Person ;
        schema:name  "Foo" .
    <http://example.com/bar> a schema:Person ;
        schema:name  "asdfsajhdfgbasdf" .

### Send a Commit
POST http://localhost/commit HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "subject": "http://localhost:8081/test",
  "created_at": 1601239744,
  "signer": "http://localhost:8081/agents/root",
  "set": {
    "https://atomicdata.dev/properties/requires": "[\"http/properties/requires\"]"
  },
  "remove": ["https://atomicdata.dev/properties/shortname"],
  "destroy": false,
  "signature": "correct_signature"
}
