### Get a thing as JSON
GET https://atomicdata.dev/properties/isA HTTP/1.1
Accept: application/json

### Get a thing as JSON-AD
GET https://atomicdata.dev/properties/isA HTTP/1.1
Accept: application/ad+json

### Get a thing as JSON-LD
GET https://atomicdata.dev/properties/isA HTTP/1.1
Accept: application/ld+json

### Get a thing as AD3
GET https://atomicdata.dev/properties/isA HTTP/1.1
Accept: application/ad3-ndjson

### Get a thing as turtle
GET https://atomicdata.dev/properties/isA HTTP/1.1
Accept: text/turtle

### Use TPF endpoint to get all atoms with an 'isA' property
GET https://atomicdata.dev/tpf?property=https://atomicdata.dev/properties/isA HTTP/1.1
Accept: application/ad3-ndjson

### Send a Commit
POST http://localhost/commit HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "subject": "http://localhost:8081/test",
  "created_at": 1601239744,
  "signer": "http://localhost:8081/agents/root",
  "set": {
    "https://atomicdata.dev/properties/requires": "[\"http/properties/requires\"]"
  },
  "remove": ["https://atomicdata.dev/properties/shortname"],
  "destroy": false,
  "signature": "correct_signature"
}

### Check if above commit has been applied correctly
GET http://localhost/somresource HTTP/1.1
Accept: application/ad3-ndjson
