export const paths = {
  agentSettings: '/app/agent',
  themeSettings: '/app/theme',
  serverSettings: '/app/server',
  new: '/app/new',
  shortcuts: '/app/shortcuts',
  search: '/app/search',
  share: '/app/share',
  show: '/app/show',
  token: '/app/token',
  data: '/app/data',
  edit: '/app/edit',
  about: '/app/about',
  import: '/app/import',
  history: '/app/history',
  allVersions: '/all-versions',
  sandbox: '/sandbox',
  confirmEmail: '/confirm-email',
  fetchBookmark: '/fetch-bookmark',
  pruneTests: '/prunetests',
};
