export const pathNames = {
  // Main app route
  app: '/app',
  // sub routes
  welcome: '/welcome',
  agentSettings: '/agent',
  appSettings: '/settings',
  sync: '/sync',
  serverSettings: '/server',
  new: '/new',
  newDrive: '/new-drive',
  shortcuts: '/shortcuts',
  search: '/search',
  share: '/share',
  show: '/show',
  token: '/token',
  data: '/data',
  edit: '/edit',
  about: '/about',
  import: '/import',
  onboarding: '/onboarding',
  history: '/history',
  allVersions: '/all-versions',
  sandbox: '/sandbox',
  fetchBookmark: '/fetch-bookmark',
  pruneTests: '/prunetests',
  linkOpenRouter: '/link-openrouter',
  devDrive: '/dev-drive',
  demo: '/demo',
  invite: '/invite',
  open: '/open',
} as const;
export const paths = {
  welcome: `${pathNames.app}${pathNames.welcome}`,
  agentSettings: `${pathNames.app}${pathNames.agentSettings}`,
  appSettings: `${pathNames.app}${pathNames.appSettings}`,
  sync: `${pathNames.app}${pathNames.sync}`,
  serverSettings: `${pathNames.app}${pathNames.serverSettings}`,
  new: `${pathNames.app}${pathNames.new}`,
  newDrive: `${pathNames.app}${pathNames.newDrive}`,
  shortcuts: `${pathNames.app}${pathNames.shortcuts}`,
  search: `${pathNames.app}${pathNames.search}`,
  share: `${pathNames.app}${pathNames.share}`,
  show: `${pathNames.app}${pathNames.show}`,
  token: `${pathNames.app}${pathNames.token}`,
  data: `${pathNames.app}${pathNames.data}`,
  edit: `${pathNames.app}${pathNames.edit}`,
  about: `${pathNames.app}${pathNames.about}`,
  import: `${pathNames.app}${pathNames.import}`,
  onboarding: `${pathNames.app}${pathNames.onboarding}`,
  history: `${pathNames.app}${pathNames.history}`,
  allVersions: `${pathNames.app}${pathNames.allVersions}`,
  sandbox: `${pathNames.app}${pathNames.sandbox}`,
  fetchBookmark: pathNames.fetchBookmark,
  pruneTests: `${pathNames.app}${pathNames.pruneTests}`,
  linkOpenRouter: `${pathNames.app}${pathNames.linkOpenRouter}`,
  devDrive: `${pathNames.app}${pathNames.devDrive}`,
  demo: `${pathNames.app}${pathNames.demo}`,
  open: `${pathNames.app}${pathNames.open}`,
} as const;
